-- 2026-07-12:  Error in executing in PRD (already correct)

ALTER TABLE public.discord_users 
ALTER COLUMN site_admin SET DEFAULT false;

-- Add missing user_id column to errors table for error-logger.js payload
ALTER TABLE public.errors
ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL;

-- Fix the id column missing a default value
ALTER TABLE public.errors
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;